version: '2'
services:
  zk:
    image: zookeeper
    network_mode: host
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: "server.1=${MESOSDEVSTACK_IP}:2181"

  master:
    image: mesosphere/mesos-master:1.2.0
    network_mode: host
    environment:
      MESOS_HOSTNAME: ${MESOSDEVSTACK_IP}
      LIBPROCESS_IP: ${MESOSDEVSTACK_IP}
      MESOS_ZK: zk://${MESOSDEVSTACK_IP}:2181/mesos
      MESOS_PORT: 5050
      MESOS_QUORUM: 1
      MESOS_REGISTRY: in_memory
      MESOS_WORK_DIR: /tmp/mesos
    depends_on:
      - zk

  slave1:
    image: mesosphere/mesos-slave:1.2.0
    network_mode: host
    pid: host
    environment:
      MESOS_MASTER: zk://${MESOSDEVSTACK_IP}:2181/mesos
      MESOS_SWITCH_USER: 0
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_WORK_DIR: /tmp/mesos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zk

  marathon:
    image: mesosphere/marathon:v1.4.2
    network_mode: host
    environment:
      MARATHON_MASTER: zk://${MESOSDEVSTACK_IP}:2181/mesos
    depends_on:
      - zk

  chronos:
    image: mesoscloud/chronos:2.4.0
    network_mode: host
    environment:
      CHRONOS_HTTP_PORT: 4400
      CHRONOS_MASTER: zk://${MESOSDEVSTACK_IP}:2181/mesos
      CHRONOS_ZK_HOSTS: zk://${MESOSDEVSTACK_IP}:2181
    depends_on:
      - zk
